/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: ImageWithAlt;
  noIndex?: boolean;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Form = {
  _type: "form";
  heading?: string;
  text?: string;
  formId?: string;
  fields?: Array<{
    key?: string;
    label?: string;
    type?: "text" | "email" | "tel" | "textarea" | "select";
    options?: Array<string>;
    required?: boolean;
    _type: "field";
    _key: string;
  }>;
  submitLabel?: string;
  successMessage?: string;
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type Locations = {
  _type: "locations";
  heading?: string;
  items?: Array<
    {
      _key: string;
    } & LocationReference
  >;
};

export type ProviderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "provider";
};

export type Providers = {
  _type: "providers";
  heading?: string;
  items?: Array<
    {
      _key: string;
    } & ProviderReference
  >;
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type Faqs = {
  _type: "faqs";
  heading?: string;
  items?: Array<
    {
      _key: string;
    } & FaqReference
  >;
};

export type Cards = {
  _type: "cards";
  heading?: string;
  intro?: string;
  items?: Array<{
    title?: string;
    text?: string;
    image?: ImageWithAlt;
    link?: Link;
    _type: "card";
    _key: string;
  }>;
};

export type Cta = {
  _type: "cta";
  heading?: string;
  text?: string;
  buttons?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type RichText = {
  _type: "richText";
  body?: PortableText;
};

export type Hero = {
  _type: "hero";
  eyebrow?: string;
  heading?: string;
  text?: string;
  image?: ImageWithAlt;
  buttons?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orgName?: string;
  tagline?: string;
  logo?: ImageWithAlt;
  contact?: {
    phone?: string;
    email?: string;
    primaryLocation?: LocationReference;
  };
  social?: Array<
    {
      _key: string;
    } & Link
  >;
  patientsNav?: {
    header?: Array<
      {
        _key: string;
      } & Link
    >;
    footer?: Array<
      {
        _key: string;
      } & Link
    >;
    cta?: Link;
  };
  providersNav?: {
    header?: Array<
      {
        _key: string;
      } & Link
    >;
    footer?: Array<
      {
        _key: string;
      } & Link
    >;
    cta?: Link;
  };
  defaultSeo?: Seo;
  ga4Id?: string;
  consent?: {
    title?: string;
    description?: string;
    policyLink?: Link;
  };
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from?: string;
  to?: string;
  permanent?: boolean;
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  effectiveDate?: string;
  body?: PortableText;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: PortableText;
  category?: string;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  image?: ImageWithAlt;
  author?: PersonReference;
  body?: PortableText;
  reviewedBy?: PersonReference;
  reviewedAt?: string;
  seo?: Seo;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: ImageWithAlt;
  address?: {
    street?: string;
    city?: string;
    region?: string;
    postalCode?: string;
    country?: string;
  };
  geo?: Geopoint;
  phone?: string;
  hours?: Array<{
    days?: Array<string>;
    opens?: string;
    closes?: string;
    _type: "hoursRange";
    _key: string;
  }>;
  providers?: Array<
    {
      _key: string;
    } & ProviderReference
  >;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Provider = {
  _id: string;
  _type: "provider";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  credentials?: string;
  slug?: Slug;
  headshot?: ImageWithAlt;
  title?: string;
  specialties?: Array<string>;
  acceptingPatients?: boolean;
  bio?: PortableText;
  locations?: Array<
    {
      _key: string;
    } & LocationReference
  >;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  image?: ImageWithAlt;
  body?: PortableText;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  providers?: Array<
    {
      _key: string;
    } & ProviderReference
  >;
  reviewedBy?: PersonReference;
  reviewedAt?: string;
  seo?: Seo;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  credentials?: string;
  role?: string;
  headshot?: ImageWithAlt;
  bio?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  audience?: "patients" | "providers";
  slug?: Slug;
  sections?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & RichText)
    | ({
        _key: string;
      } & Cta)
    | ({
        _key: string;
      } & Cards)
    | ({
        _key: string;
      } & Faqs)
    | ({
        _key: string;
      } & Providers)
    | ({
        _key: string;
      } & Locations)
    | ({
        _key: string;
      } & Form)
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | Seo
  | PortableText
  | Link
  | SanityImageAssetReference
  | ImageWithAlt
  | Form
  | LocationReference
  | Locations
  | ProviderReference
  | Providers
  | FaqReference
  | Faqs
  | Cards
  | Cta
  | RichText
  | Hero
  | Settings
  | Redirect
  | LegalPage
  | Slug
  | Faq
  | PersonReference
  | Post
  | Location
  | Geopoint
  | Provider
  | Service
  | Person
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;
